# Generated by Django 3.0 on 2020-11-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
